### ISSUE TITLE
three questions about interPlan 

### ISSUE THREAD

**Issue by jessapinkman** [mh0797/interPlan#2] opened 2024-05-07 12:34 UTC
hi, nice work! Thanks for your contribution. After reading the paper, three questions I have.

First, you provide two different scenario filters: all 335 scenarios and 10 scenarios per type. Why not use all scenarios for evaluation? Don't you think 80 is limited?

Second, incentivizing lane changes by augmenting the goal of original nuPlan scenarios. That is great. So Three-eighths(30/80) of the scenes are "Interactive lane change" scenes, but counterintuitively, the rules method performs best. Could you please explain it?

Third, interplan implements a new IDM control strategy, i.e.,  assertive policy. So interplan only reacts to the EV in lane changing scenarios? What if you make an unprotected left turn or need to drive to the opposite lane to overtake in Acc. site?

**Comment by mh0797** [comment] 2024-05-07 14:04
Hi @jessapinkman,
thanks for your feedback and interest in interPlan. 
Please find answers to your questions below:

## Why only use 80 scenarios and not all 335 scenarios
Interplan comes with 50 difficult long-tail scenarios and 285 interactive lane-change scenarios. To balance them, we decided to use 10 scenarios of each type (there are 3 different types of lane changes referring to different traffic densities), resulting in 80 scenarios. The lane-change scenarios are quite similar to each other, so using 30 of them already provides profound insights into a planner's capabilities. 
In this repository, we provide scenario filters to run on either the 80 scenarios (`interplan10`) or use all 335 scenarios (`benchmark_scenarios`).

## Why do the rule-based methods perform best in lane-change scenarios?
This seems counterintuitive at first glance since some rule-based methods, such as IDM, are by design unable to do lane changes. However, while they don't reach the goal lane, they do not cause collisions when attempting lane changes. Moreover, they usually produce very comfortable plans. Therefore, they outperform other (learning-based) planners, which often cause collisions when trying to do lane changes.
Note: this also underlines the importance of different traffic densities because, in high-traffic density, some planners simply don't attempt to do lane changes at all, whereas, in medium traffic density, they do try to change lanes and sometimes exhibit critical shortcomings w.r.t. safety so that they cause collisions.


## How does the assertive / conservative IDM policy behave in unprotected turns etc.?
IDM is a lane-following model that does not really perform well in intersections. nuPlan mitigates this by making IDM comply with stop lines, traffic lights, etc. The augmented IDM policy does not change the behavior in these scenarios. We implemented it only for the purpose of generating more diverse traffic in lane-change scenarios. 


Let me know if you have any more questions. I am closing this issue for now - Feel free to reopen it.

**Closed as completed by mh0797** 2024-05-07 14:04 UTC
