### ISSUE TITLE
Request More Details on How to Run Simulation

### ISSUE THREAD

**Issue by ZiWang1105** [mh0797/interPlan#3] opened 2024-05-29 03:55 UTC
Hello, thanks for your awesome work! Could you please provide more details on how to modify `scripts/sim_pdm_closed.sh` to run the simulation? For example, where should I place the checkpoints? I just followed your instruction in README but encountered the following error:

`assert len(runners) > 0, 'No scenarios found to simulate!'
AssertionError: No scenarios found to simulate!`

Do you know how to solve it?

Thanks!

**Comment by ZiWang1105** [comment] 2024-05-29 04:00
In addition, could you share the file structure for nuplan-devkit, tuplan-garage, and interplan? How should these three repositories be organized?

**Comment by mh0797** [comment] 2024-05-29 06:21
Hi @ZiWang1105,
thanks for using interPlan.

# How to organize the repositories.
You can organize them as you wish as long as they are installed with `pip install -e .`. Then, all the imports will work independently of where the repos are located. However, I recommend having them all in one workspace folder. This makes maintenance easier. This is, however, no requirement.

# How do you need to modify the scripts?
You don't have to modify them at all. PDM-Closed is a rule-based planner so no checkpoint is required. For learning-based planners, you can check the tuplan-garage to see how to include the checkpoint in the simulation script.

# Why are no scenarios found?
It's hard to tell the reason for this without extra details. Did you download and set up the nuPlan dataset properly including all required environment-variables?

**Comment by ZiWang1105** [comment] 2024-05-29 16:21
Thanks for your reply! The first and second answers make sense and solved my confusion. For the third question, I think yes because I can run the pdm_closed simulation scripts in tuplan_garage successfully. But I think it is caused by the difference between my environment-variables and yours or there are some paths hard-coded in interPlan. May I have a look at your environment variables?

**Comment by mh0797** [comment] 2024-06-10 08:16
Hi @ZiWang1105,

I was able to reproduce the issue. It occurs if you are lacking the test split.
So to fix it, you need to download the test logs and save them in the folder called `trainval` (see [here](https://github.com/motional/nuplan-devkit/blob/master/docs/dataset_setup.md))

I am closing this for now. Feel free to re-open if the issue persists.

**Closed as completed by mh0797** 2024-06-10 08:16 UTC
